import { Question } from "@/components/MCQCard";

export const biologyHardQuestions: Question[] = [
  // Cell Biology
  {
    question: "Which organelle is responsible for the synthesis of ATP through oxidative phosphorylation?",
    options: ["Ribosome", "Mitochondria", "Golgi apparatus", "Endoplasmic reticulum"],
    correctIndex: 1,
    explanation: "Mitochondria are the powerhouse of the cell. Oxidative phosphorylation occurs on the inner mitochondrial membrane where ATP synthase uses the proton gradient generated by the electron transport chain to synthesize ATP."
  },
  {
    question: "During which phase of meiosis does crossing over occur?",
    options: ["Prophase I", "Metaphase I", "Anaphase II", "Telophase I"],
    correctIndex: 0,
    explanation: "Crossing over (synapsis and recombination) occurs during prophase I of meiosis when homologous chromosomes pair up to form tetrads. This process increases genetic diversity by exchanging segments between non-sister chromatids."
  },
  {
    question: "Which of the following is NOT a function of the rough endoplasmic reticulum?",
    options: ["Protein synthesis", "Glycosylation", "Lipid synthesis", "Protein folding"],
    correctIndex: 2,
    explanation: "Lipid synthesis is primarily carried out by the smooth endoplasmic reticulum (SER). The rough ER is studded with ribosomes and is involved in protein synthesis, glycosylation (addition of sugar chains), and protein folding."
  },
  {
    question: "What is the primary role of cyclin-dependent kinases (CDKs) in the cell cycle?",
    options: ["DNA replication", "Cell division regulation", "Apoptosis", "Protein synthesis"],
    correctIndex: 1,
    explanation: "CDKs are key regulators of the cell cycle. They form complexes with cyclins to phosphorylate target proteins that drive the cell through different phases of the cell cycle (G1, S, G2, M)."
  },
  {
    question: "Which process converts NADH back to NAD⁺ during anaerobic respiration in muscle cells?",
    options: ["Glycolysis", "Lactic acid fermentation", "Krebs cycle", "Electron transport chain"],
    correctIndex: 1,
    explanation: "During anaerobic respiration in muscles, pyruvate is reduced to lactate by lactate dehydrogenase, which simultaneously oxidizes NADH to NAD⁺. This NAD⁺ is then reused in glycolysis."
  },
  {
    question: "The fluid mosaic model describes the structure of which cellular component?",
    options: ["Cell wall", "Cell membrane", "Nuclear envelope", "Mitochondrial membrane"],
    correctIndex: 1,
    explanation: "The fluid mosaic model, proposed by Singer and Nicolson (1972), describes the cell membrane as a phospholipid bilayer with embedded proteins that can move laterally, giving it fluid and mosaic characteristics."
  },
  // Genetics
  {
    question: "In a dihybrid cross between two heterozygous parents (AaBb × AaBb), what is the expected phenotypic ratio in the F2 generation?",
    options: ["9:3:3:1", "1:1:1:1", "3:1", "9:6:1"],
    correctIndex: 0,
    explanation: "In a dihybrid cross with independent assortment, the F2 generation shows a 9:3:3:1 ratio. This means 9/16 show both dominant traits, 3/16 show first dominant only, 3/16 show second dominant only, and 1/16 show both recessive traits."
  },
  {
    question: "Which type of mutation changes a codon to a STOP codon?",
    options: ["Missense", "Nonsense", "Silent", "Frameshift"],
    correctIndex: 1,
    explanation: "A nonsense mutation changes a sense codon (coding for an amino acid) into a premature STOP codon (UAA, UAG, or UGA), resulting in a truncated and usually nonfunctional protein."
  },
  {
    question: "What is the function of telomerase in eukaryotic cells?",
    options: ["DNA repair", "Telomere extension", "Chromosome condensation", "Histone modification"],
    correctIndex: 1,
    explanation: "Telomerase is a ribonucleoprotein enzyme that adds repetitive DNA sequences (TTAGGG in humans) to the ends of chromosomes (telomeres), preventing their shortening during cell division."
  },
  {
    question: "The lac operon in E. coli is an example of:",
    options: ["Positive regulation", "Negative regulation", "Both positive and negative regulation", "Constitutive expression"],
    correctIndex: 2,
    explanation: "The lac operon exhibits both positive and negative regulation. It is negatively regulated by the lac repressor (LacI) which binds the operator in the absence of lactose, and positively regulated by CAP-cAMP when glucose is absent."
  },
  {
    question: "Which type of RNA carries amino acids to the ribosome during translation?",
    options: ["mRNA", "tRNA", "rRNA", "snRNA"],
    correctIndex: 1,
    explanation: "Transfer RNA (tRNA) carries specific amino acids to the ribosome. Each tRNA has an anticodon that pairs with the complementary codon on mRNA, ensuring the correct amino acid is added to the growing polypeptide chain."
  },
  {
    question: "In sickle cell anemia, a single nucleotide change in the β-globin gene results in:",
    options: ["Glu → Val at position 6", "His → Leu at position 6", "Val → Glu at position 6", "Leu → His at position 6"],
    correctIndex: 0,
    explanation: "Sickle cell anemia is caused by a point mutation (GAG → GTG) in the β-globin gene, resulting in the substitution of glutamic acid (Glu) with valine (Val) at position 6 of the β-globin chain."
  },
  {
    question: "Which of the following is a characteristic of mitochondrial inheritance?",
    options: ["Father-to-child transmission", "Mother-to-child transmission", "X-linked pattern", "Autosomal dominant pattern"],
    correctIndex: 1,
    explanation: "Mitochondrial DNA is inherited exclusively from the mother (maternal inheritance) because mitochondria in the sperm are typically degraded after fertilization. This results in mother-to-child transmission of mitochondrial disorders."
  },
  // Human Physiology
  {
    question: "The Frank-Starling mechanism of the heart describes:",
    options: ["Relationship between heart rate and blood pressure", "Relationship between end-diastolic volume and stroke volume", "Effect of sympathetic stimulation on heart rate", "Regulation of cardiac output by the brain"],
    correctIndex: 1,
    explanation: "The Frank-Starling mechanism states that the stroke volume of the heart increases in response to an increase in the volume of blood filling the ventricles (end-diastolic volume), within physiological limits."
  },
  {
    question: "Which hormone is primarily responsible for the regulation of blood calcium levels through its action on bones, kidneys, and intestines?",
    options: ["Thyroxine", "Calcitonin", "Parathyroid hormone (PTH)", "Aldosterone"],
    correctIndex: 2,
    explanation: "PTH is secreted by the parathyroid glands when blood calcium is low. It increases calcium levels by stimulating osteoclast activity in bones, increasing calcium reabsorption in kidneys, and promoting activation of vitamin D for intestinal absorption."
  },
  {
    question: "The Countercurrent multiplier system is found in:",
    options: ["Liver", "Lung", "Kidney (Loop of Henle)", "Thyroid gland"],
    correctIndex: 2,
    explanation: "The countercurrent multiplier system operates in the Loop of Henle of the nephron. The descending limb is permeable to water while the ascending limb actively transports NaCl, creating an osmotic gradient in the medulla that concentrates urine."
  },
  {
    question: "Which neurotransmitter is primarily involved at the neuromuscular junction?",
    options: ["Dopamine", "GABA", "Acetylcholine", "Serotonin"],
    correctIndex: 2,
    explanation: "Acetylcholine (ACh) is released at the neuromuscular junction and binds to nicotinic receptors on the motor end plate of skeletal muscle fibers, triggering muscle contraction through depolarization."
  },
  {
    question: "Which blood vessels have the highest resistance to blood flow?",
    options: ["Aorta", "Capillaries", "Arterioles", "Venules"],
    correctIndex: 2,
    explanation: "Arterioles have the highest resistance to blood flow (highest total peripheral resistance) because of their small diameter and thick smooth muscle walls. They are the primary site of vascular resistance regulation."
  },
  {
    question: "The respiratory exchange ratio (RER) indicates:",
    options: ["The ratio of O₂ consumed to CO₂ produced", "The ratio of CO₂ produced to O₂ consumed", "The total lung capacity", "The tidal volume"],
    correctIndex: 1,
    explanation: "RER = VCO₂/VO₂ (volume of CO₂ produced divided by volume of O₂ consumed). An RER of 1.0 indicates pure carbohydrate metabolism, while 0.7 indicates pure fat metabolism."
  },
  {
    question: "Which of the following hormones stimulates the release of bile from the gallbladder?",
    options: ["Gastrin", "Secretin", "Cholecystokinin (CCK)", "Gastric inhibitory peptide (GIP)"],
    correctIndex: 2,
    explanation: "Cholecystokinin (CCK) is released by I-cells in the duodenum in response to fats and proteins. It stimulates gallbladder contraction (releasing bile) and pancreatic enzyme secretion."
  },
  {
    question: "Which of the following is the most abundant protein in the human body?",
    options: ["Hemoglobin", "Albumin", "Collagen", "Keratin"],
    correctIndex: 2,
    explanation: "Collagen is the most abundant protein, making up about 30% of total body protein. It provides structural support to skin, bones, tendons, ligaments, and connective tissues throughout the body."
  },
  // Plant Physiology
  {
    question: "Which pigment is primarily responsible for the light-dependent reactions of photosynthesis?",
    options: ["Carotenoids", "Chlorophyll a", "Phycocyanin", "Xanthophyll"],
    correctIndex: 1,
    explanation: "Chlorophyll a is the primary pigment that participates directly in the light-dependent reactions. It is the only pigment that can transfer light energy to the reaction center (P680 in PSII and P700 in PSI) for photochemical conversion."
  },
  {
    question: "The Calvin cycle takes place in:",
    options: ["Thylakoid membrane", "Stroma of chloroplast", "Cytoplasm", "Mitochondrial matrix"],
    correctIndex: 1,
    explanation: "The Calvin cycle (light-independent reactions) occurs in the stroma of chloroplasts. Here, CO₂ is fixed into organic molecules using ATP and NADPH produced in the light-dependent reactions."
  },
  {
    question: "Which plant hormone is primarily responsible for cell elongation and apical dominance?",
    options: ["Cytokinin", "Gibberellin", "Auxin", "Abscisic acid"],
    correctIndex: 2,
    explanation: "Auxin (primarily IAA - indole-3-acetic acid) is produced in the apical meristem and promotes cell elongation, maintains apical dominance, and influences phototropism and gravitropism."
  },
  {
    question: "What is the primary function of transpiration in plants?",
    options: ["CO₂ absorption", "Water and mineral transport", "Oxygen release", "Sugar transport"],
    correctIndex: 1,
    explanation: "Transpiration creates a negative pressure (tension) that pulls water and dissolved minerals from roots through the xylem to leaves. This is the main driving force for water transport in plants (cohesion-tension theory)."
  },
  {
    question: "CAM plants minimize photorespiration by:",
    options: ["Opening stomata only at night", "Fixing CO₂ into C4 compounds", "Having thick, waxy cuticles", "Using bundle sheath cells"],
    correctIndex: 0,
    explanation: "CAM (Crassulacean Acid Metabolism) plants open their stomata at night (when it's cooler) to fix CO₂ into malate, which is stored in vacuoles. During the day, stomata close to conserve water, and malate is released to provide CO₂ for the Calvin cycle."
  },
  // Ecology
  {
    question: "Which of the following represents a density-dependent factor in population regulation?",
    options: ["Flood", "Disease", "Wildfire", "Drought"],
    correctIndex: 1,
    explanation: "Disease is density-dependent because its transmission rate increases with population density. As populations become more crowded, infectious diseases spread more easily, acting as a regulatory mechanism."
  },
  {
    question: "The 10% rule in ecology states that:",
    options: ["10% of species are keystone species", "Only 10% of energy is transferred between trophic levels", "10% of a habitat should be protected", "Only 10% of individuals survive"],
    correctIndex: 1,
    explanation: "The 10% rule states that approximately 10% of the energy at one trophic level is transferred to the next. The remaining 90% is lost as heat through metabolism (cellular respiration)."
  },
  {
    question: "Which ecological term describes the role of an organism within its ecosystem?",
    options: ["Habitat", "Niche", "Biome", "Population"],
    correctIndex: 1,
    explanation: "An ecological niche describes the functional role of an organism in its ecosystem, including its diet, habitat, interactions with other species, and how it uses resources. It is broader than habitat alone."
  },
  {
    question: "Succession that occurs on previously uninhabited land (e.g., bare rock from a volcanic eruption) is called:",
    options: ["Secondary succession", "Primary succession", "Climax community", "Pioneer community"],
    correctIndex: 1,
    explanation: "Primary succession occurs on barren land where no previous ecosystem existed, such as bare rock, lava flows, or retreating glaciers. Pioneer species like lichens colonize first, gradually building soil for later species."
  },
  // Enzymes & Biomolecules
  {
    question: "Which type of enzyme inhibition can be overcome by increasing substrate concentration?",
    options: ["Non-competitive inhibition", "Competitive inhibition", "Irreversible inhibition", "Allosteric inhibition"],
    correctIndex: 1,
    explanation: "In competitive inhibition, the inhibitor competes with the substrate for the active site. Increasing substrate concentration can outcompete the inhibitor, eventually achieving maximum velocity (Vmax)."
  },
  {
    question: "The Michaelis constant (Km) represents:",
    options: ["The maximum reaction velocity", "The substrate concentration at half Vmax", "The enzyme concentration", "The inhibition constant"],
    correctIndex: 1,
    explanation: "Km is the substrate concentration at which the reaction velocity is half of Vmax. A lower Km indicates higher enzyme affinity for the substrate, while a higher Km indicates lower affinity."
  },
  {
    question: "Which type of enzyme regulation involves the binding of a molecule at a site other than the active site?",
    options: ["Competitive inhibition", "Allosteric regulation", "Covalent modification", "Feedback inhibition"],
    correctIndex: 1,
    explanation: "Allosteric regulation involves the binding of regulatory molecules (activators or inhibitors) at allosteric sites, which are distinct from the active site. This binding induces conformational changes that affect enzyme activity."
  },
  {
    question: "Which of the following is a feature of enzymes that makes them different from inorganic catalysts?",
    options: ["They increase activation energy", "They are consumed during reactions", "They exhibit substrate specificity", "They work at high temperatures"],
    correctIndex: 2,
    explanation: "Enzymes are highly specific for their substrates due to the precise shape and chemical properties of their active sites (lock and key model or induced fit model). Inorganic catalysts are generally less specific."
  },
  {
    question: "Denaturation of an enzyme typically results in:",
    options: ["Increased activity", "Loss of quaternary structure only", "Loss of three-dimensional structure and activity", "Changes in primary structure only"],
    correctIndex: 2,
    explanation: "Denaturation disrupts the secondary, tertiary, and quaternary structures of enzymes (but not primary structure), causing loss of the active site shape and therefore loss of catalytic activity."
  },
  // Evolution
  {
    question: "Which type of natural selection favors intermediate phenotypes and selects against extremes?",
    options: ["Directional selection", "Disruptive selection", "Stabilizing selection", "Sexual selection"],
    correctIndex: 2,
    explanation: "Stabilizing selection favors the intermediate phenotype and selects against both extreme phenotypes. For example, human birth weight is stabilized around 3.5 kg, with higher mortality for very low or very high birth weights."
  },
  {
    question: "The Hardy-Weinberg principle states that allele frequencies in a population will remain constant in the absence of:",
    options: ["Natural selection only", "Genetic drift only", "Evolutionary forces", "Mutation only"],
    correctIndex: 2,
    explanation: "The Hardy-Weinberg equilibrium states that allele frequencies remain constant across generations in the absence of all evolutionary forces: natural selection, genetic drift, gene flow, mutation, and non-random mating."
  },
  {
    question: "Which of the following is an example of convergent evolution?",
    options: ["Wings of bats and birds", "Forelimbs of whales and humans", "Eyes of octopus and humans", "Both A and C"],
    correctIndex: 3,
    explanation: "Convergent evolution produces similar structures in unrelated species due to similar selective pressures. Wings of bats (mammals) and birds evolved independently, as did camera eyes in octopuses and vertebrates."
  },
  // Biological Molecules
  {
    question: "Which polysaccharide serves as the primary energy storage molecule in animals?",
    options: ["Cellulose", "Starch", "Glycogen", "Chitin"],
    correctIndex: 2,
    explanation: "Glycogen is the primary energy storage polysaccharide in animals. It is stored mainly in liver and muscle cells as highly branched granules that can be quickly broken down into glucose when energy is needed."
  },
  {
    question: "Which type of lipid is a major component of cell membranes and also serves as a precursor for steroid hormones?",
    options: ["Triglycerides", "Phospholipids", "Cholesterol", "Fatty acids"],
    correctIndex: 2,
    explanation: "Cholesterol is a sterol that is a key component of animal cell membranes (regulating fluidity) and serves as the precursor for steroid hormones (testosterone, estrogen, cortisol, etc.), bile salts, and vitamin D."
  },
  {
    question: "The tertiary structure of a protein is stabilized by all of the following EXCEPT:",
    options: ["Disulfide bonds", "Hydrogen bonds", "Peptide bonds", "Hydrophobic interactions"],
    correctIndex: 2,
    explanation: "Peptide bonds stabilize the primary structure (amino acid sequence) of proteins. Tertiary structure is stabilized by disulfide bonds, hydrogen bonds, ionic bonds, van der Waals forces, and hydrophobic interactions between R-groups."
  },
  // Morphology & Anatomy
  {
    question: "Which type of joint allows the greatest range of motion?",
    options: ["Sutures", "Hinge joint", "Ball and socket joint", "Pivot joint"],
    correctIndex: 2,
    explanation: "Ball and socket joints (e.g., shoulder and hip) allow the greatest range of motion, including flexion, extension, abduction, adduction, circumduction, and rotation. They are classified as multiaxial diarthrodial joints."
  },
  {
    question: "The epiglottis prevents food from entering the:",
    options: ["Esophagus", "Trachea", "Pharynx", "Nasal cavity"],
    correctIndex: 1,
    explanation: "The epiglottis is a flap of cartilage that covers the glottis (opening of the larynx/trachea) during swallowing, directing food into the esophagus and preventing aspiration into the airway."
  },
  {
    question: "Which type of blood cell is primarily responsible for the immune response against parasites?",
    options: ["Neutrophils", "Lymphocytes", "Eosinophils", "Monocytes"],
    correctIndex: 2,
    explanation: "Eosinophils are granulocytes that play a key role in defense against parasitic infections (especially helminths) and are also involved in allergic reactions. They release toxic granule contents to destroy parasites."
  },
  {
    question: "Hemoglobin has a higher affinity for oxygen when:",
    options: ["pH is low and temperature is high", "pH is high and temperature is low", "CO₂ concentration is high", "2,3-BPG levels are high"],
    correctIndex: 1,
    explanation: "Hemoglobin has higher O₂ affinity at high pH (low H⁺) and low temperature (left-shifted oxygen dissociation curve). This occurs in the lungs where pH is higher and temperature is lower, facilitating O₂ loading."
  },
  {
    question: "The sinoatrial (SA) node is the heart's natural pacemaker because:",
    options: ["It has the fastest conduction velocity", "It generates spontaneous action potentials", "It connects atria to ventricles", "It receives the most parasympathetic input"],
    correctIndex: 1,
    explanation: "The SA node spontaneously depolarizes (has automaticity) at approximately 75 beats per minute, faster than any other part of the heart. This spontaneous depolarization (funny current, If) makes it the primary pacemaker."
  },
  {
    question: "Antibodies are produced by:",
    options: ["T-helper cells", "B-lymphocytes (plasma cells)", "Macrophages", "Natural killer cells"],
    correctIndex: 1,
    explanation: "Antibodies (immunoglobulins) are produced by plasma cells, which are differentiated B-lymphocytes. Each plasma cell produces antibodies specific to one antigen epitope, contributing to humoral immunity."
  },
  {
    question: "Which vitamin deficiency causes night blindness?",
    options: ["Vitamin A", "Vitamin B12", "Vitamin C", "Vitamin D"],
    correctIndex: 0,
    explanation: "Vitamin A (retinol) is essential for the synthesis of rhodopsin, the photopigment in rod cells of the retina. Deficiency leads to nyctalopia (night blindness) and can progress to xerophthalmia."
  },
  {
    question: "The glomerular filtration rate (GFR) is primarily regulated by:",
    options: ["Afferent arteriole constriction/dilation", "Efferent arteriole constriction/dilation", "Both afferent and efferent arterioles", "Collecting duct reabsorption"],
    correctIndex: 2,
    explanation: "GFR is regulated by both afferent and efferent arterioles. Constriction of the afferent arteriole decreases GFR, while constriction of the efferent arteriole increases GFR. Autoregulation, sympathetic input, and hormones all modulate both."
  },
  {
    question: "Which of the following is a function of the liver in metabolism?",
    options: ["Insulin production", "Gluconeogenesis", "Thyroid hormone synthesis", "Red blood cell production"],
    correctIndex: 1,
    explanation: "The liver performs gluconeogenesis (synthesis of glucose from non-carbohydrate sources like amino acids, lactate, and glycerol), especially during fasting. It also stores glycogen, synthesizes plasma proteins, and detoxifies substances."
  },
  {
    question: "The basal metabolic rate (BMR) is most affected by:",
    options: ["Physical activity level", "Thyroid hormone levels", "Diet composition", "Sleep duration"],
    correctIndex: 1,
    explanation: "Thyroid hormones (T3 and T4) are the primary regulators of BMR. Hyperthyroidism increases BMR while hypothyroidism decreases it. Other factors like age, sex, body composition, and fasting also affect BMR."
  },
  {
    question: "Which structure in the kidney is responsible for the concentration of urine?",
    options: ["Glomerulus", "Bowman's capsule", "Collecting duct", "Proximal convoluted tubule"],
    correctIndex: 2,
    explanation: "The collecting duct passes through the hypertonic medulla. In the presence of ADH (antidiuretic hormone), the collecting duct becomes permeable to water, allowing water reabsorption and concentration of urine."
  },
  {
    question: "Oxygen dissociation curve shifts to the RIGHT when:",
    options: ["Temperature decreases", "pH increases (becomes more alkaline)", "CO₂ levels increase", "2,3-BPG decreases"],
    correctIndex: 2,
    explanation: "A right shift indicates decreased O₂ affinity (Bohr effect), facilitating O₂ unloading to tissues. This occurs with increased CO₂, increased temperature, decreased pH (more acidic), and increased 2,3-BPG — all conditions found in actively metabolizing tissues."
  },
  {
    question: "The primary site of nutrient absorption in the human digestive system is:",
    options: ["Stomach", "Small intestine (jejunum)", "Large intestine", "Duodenum"],
    correctIndex: 1,
    explanation: "The jejunum of the small intestine is the primary site for absorption of most nutrients (amino acids, monosaccharides, fatty acids, vitamins, minerals). The villi and microvilli increase surface area for efficient absorption."
  },
  {
    question: "Which of the following correctly describes the cardiac cycle?",
    options: ["Systole → Isovolumetric relaxation → Diastole → Isovolumetric contraction", "Atrial systole → Ventricular systole → Diastole", "Isovolumetric contraction → Ejection → Isovolumetric relaxation → Filling", "Diastole → Systole → Isovolumetric relaxation"],
    correctIndex: 2,
    explanation: "The cardiac cycle consists of: (1) Isovolumetric contraction (all valves closed, pressure rises), (2) Ejection (semilunar valves open, blood pumped out), (3) Isovolumetric relaxation (all valves closed), (4) Filling (AV valves open, ventricles fill with blood)."
  },
  {
    question: "Which of the following is NOT a characteristic of prokaryotic cells?",
    options: ["Circular DNA", "70S ribosomes", "Membrane-bound nucleus", "Cell wall with peptidoglycan"],
    correctIndex: 2,
    explanation: "Prokaryotic cells lack a membrane-bound nucleus. Their DNA is found in the nucleoid region. They also lack other membrane-bound organelles like mitochondria, ER, and Golgi apparatus."
  },
  {
    question: "DNA replication is described as semiconservative because:",
    options: ["Only one strand is replicated", "Each new molecule has one old and one new strand", "Replication occurs only in S phase", "Both strands are newly synthesized"],
    correctIndex: 1,
    explanation: "Meselson and Stahl's experiment (1958) proved that DNA replication is semiconservative: each daughter molecule contains one parental (original) strand and one newly synthesized strand."
  },
  {
    question: "Which of the following mutations is least likely to affect protein function?",
    options: ["Frameshift mutation in coding region", "Nonsense mutation in coding region", "Silent mutation in coding region", "Missense mutation in active site"],
    correctIndex: 2,
    explanation: "A silent (synonymous) mutation changes the DNA codon but not the amino acid (due to degeneracy of the genetic code), so the protein sequence remains unchanged and function is unaffected."
  },
  {
    question: "Which blood group is known as the universal donor?",
    options: ["A positive", "B negative", "AB positive", "O negative"],
    correctIndex: 3,
    explanation: "O negative blood lacks A, B, and Rh antigens on red blood cells, so it can be transfused to patients of any blood type without causing an immune reaction. However, O negative individuals can only receive O negative blood."
  },
  {
    question: "The renin-angiotensin-aldosterone system (RAAS) primarily regulates:",
    options: ["Blood glucose levels", "Blood pressure and fluid balance", "Calcium metabolism", "Body temperature"],
    correctIndex: 1,
    explanation: "RAAS regulates blood pressure and fluid balance. Renin converts angiotensinogen to angiotensin I, which is converted to angiotensin II. Angiotensin II causes vasoconstriction and stimulates aldosterone release, promoting sodium and water retention."
  },
  {
    question: "Which of the following is an example of codominance?",
    options: ["Skin color inheritance", "ABO blood group inheritance", "Height inheritance", "Eye color inheritance"],
    correctIndex: 1,
    explanation: "ABO blood groups demonstrate codominance: when both A and B alleles are present (genotype IAIB), both antigens are expressed equally on red blood cells, resulting in blood type AB."
  },
  {
    question: "The enzyme responsible for unwinding the DNA double helix during replication is:",
    options: ["DNA polymerase", "DNA ligase", "Helicase", "Primase"],
    correctIndex: 2,
    explanation: "Helicase breaks the hydrogen bonds between complementary base pairs, unwinding the DNA double helix to create the replication fork. It works in conjunction with single-strand binding proteins to stabilize the unwound strands."
  },
  {
    question: "Which of the following structures is found in plant cells but NOT in animal cells?",
    options: ["Ribosomes", "Mitochondria", "Central vacuole", "Golgi apparatus"],
    correctIndex: 2,
    explanation: "The central vacuole is a large, membrane-bound organelle found in mature plant cells that stores water, nutrients, and waste products. It maintains turgor pressure, which provides structural support to the plant."
  },
  {
    question: "What is the role of mRNA in protein synthesis?",
    options: ["Carries amino acids to ribosomes", "Transfers genetic code from DNA to ribosomes", "Forms the structural component of ribosomes", "Catalyzes peptide bond formation"],
    correctIndex: 1,
    explanation: "Messenger RNA (mRNA) carries the genetic information from DNA (in the nucleus) to ribosomes (in the cytoplasm), where it serves as a template for protein synthesis during translation."
  },
  {
    question: "Which of the following is NOT a function of proteins?",
    options: ["Enzymatic catalysis", "Structural support", "Long-term energy storage", "Immune defense"],
    correctIndex: 2,
    explanation: "Proteins serve many functions (enzymes, structure, transport, defense, signaling, movement) but long-term energy storage is primarily the role of lipids (fats) and carbohydrates (glycogen/starch)."
  },
];
